### ISSUE TITLE
Frontend: Contact us

### ISSUE THREAD

**Issue by h09shais** [HackYourFuture-CPH/fp-class19#10]
## User story

**Who:** **As a** developer
**What:** **I want to** be able to display the Contact Page
**Why:** **so that I can** show that info to the users.

## Acceptance criteria

Create a React component like the one we can see below
 
![Screen Shot 2022-01-20 at 11 13 35](https://user-images.githubusercontent.com/8406654/150318963-1805c1f7-304e-485d-b3e4-677851a8b4ef.png)

Check the wireframes here: https://www.figma.com/file/yo4QT2EcPo83HAMI3ydMxb/HYF-Wireframes?node-id=4%3A1324

## Implementation details

Download the images from the wireframes and add them to this folder src/client/assets/images

Add a folder called fonts under assets - /src/client/assets/ and add the font files.

**Comment by FlorentinaPetica** [comment]
Hey good job Divya it's looks like the wyreframes and it shows well. I just notices one small thing for the maming of the React component it is not following the rules from the CheatSheet fx. Contact.component.js and the css file Contact.styles.css. Other than that it's good to go. 👍
