### ISSUE TITLE
Payment-Page

### ISSUE THREAD

**Issue by suvarna-ratna** [HackYourFuture-CPH/fp-class19#100]
## **User story**
Who: As a developer
What: I want to be have a Payment page
Why: so if user can go to this page for payment 

## **Acceptance criteria**
Create a storybook component for display of Form like the one we can see below
<img width="311" alt="Screenshot 2022-02-08 at 13 56 43" src="https://user-images.githubusercontent.com/81093589/152991410-0fd293ab-0b4e-4e82-8e9f-b86f3a783fb5.png">

## **Check the wireframes here:**
https://www.figma.com/file/yo4QT2EcPo83HAMI3ydMxb/HYF-Wireframes?node-id=216%3A28468

**Implementation details**
You will need to include the button component

**Comment by dpfernandes** [comment]
This issue is not needed because this window belongs to PayPal

**Comment by dpfernandes** [comment]
This is the new issue for the payment/paypal https://github.com/HackYourFuture-CPH/fp-class19/issues/206.
