### ISSUE TITLE
Fix: LoginForm

### ISSUE THREAD

**Issue by suvarna-ratna** [HackYourFuture-CPH/fp-class19#139]
## **User story**
Who: As a developer
What: I want to change some part in this form ** Log In with Google**
Why: previously it was an image but now fix it to html button

## **Acceptance criteria**
Create a storybook component for display of Form like the one we can see below
<img width="478" alt="Screenshot 2022-02-15 at 12 11 55" src="https://user-images.githubusercontent.com/81093589/154050776-8f17dfc0-19e0-43a5-bf98-0f44c0a146c3.png">
Check the wireframes here:
https://www.figma.com/file/yo4QT2EcPo83HAMI3ydMxb/HYF-Wireframes?node-id=216%3A28468

## **Implementation details**
Dowload google icon 
<img width="29" alt="Screenshot 2022-02-15 at 12 18 09" src="https://user-images.githubusercontent.com/81093589/154051692-a9ffa13b-fd6c-4fd6-a504-989b58e2b007.png">

**Comment by Impressiv3** [comment]
![image](https://user-images.githubusercontent.com/81259898/154667036-a7939dbd-d8b7-4e3a-856b-ef1c4d70ed49.png)

**Comment by Impressiv3** [comment]
![image](https://user-images.githubusercontent.com/81259898/154667258-64f9cac3-cbf0-4672-9b84-170bd7605f90.png)
This should probably be changed at some point :D
