### ISSUE TITLE
Frontend: small changes on Aboutus&Contactus container

### ISSUE THREAD

**Issue by JiuTak** [HackYourFuture-CPH/fp-class19#158]
## User story

**Who**: As a developer
**What**: I want to fix the display problem
**Why**: So that I can display AboutUs & Contact Us page properly.

## Acceptance criteria

The current develop page looks like this.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/84173609/154646781-f80defab-1734-445a-89d3-1fc0040b61f0.png">
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/84173609/154646832-9f8d1e59-2b43-4d53-8531-81cdc065629b.png">

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/84173609/154647019-b019e0a0-84d7-4022-b1b3-c3810790ba46.png">
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/84173609/154647082-f01c3f17-4dbd-4c81-b510-3a4a37716eae.png">

## Implementation details

**Comment by santhoshboinapally** [comment]
This task already done in this PR **Frontend landing page container #120** .
