### ISSUE TITLE
Databases: Create Products table ( Migrations + Seeds )

### ISSUE THREAD

**Issue by Impressiv3** [HackYourFuture-CPH/fp-class19#18]
## User story

**Who:** **As a** developer
**What:** **I want to** create the PRODUCTS table in the Database using Knex + add migrations and seeds.
**Why:** **so that I can** save new PRODUCTS and mock data that I can retrieve later.

## Acceptance criteria

PRODUCTS table has been created with all the required fields. ( migration and seed files can be run from the command line using Knex )

![image](https://user-images.githubusercontent.com/81259898/150698791-25c639f7-f8ee-4d10-b095-7afa437f1e52.png)

 
## Implementation details
No details yet... TODO

- [x] **category has been removed**
- [x] **updated_at field has been added**
- [x] **is_on_discount field has been added** 
- [x]  **discount_percent has been added**
- [x] **is_available has been added** 
- [x] **picture field has been changed to default to static url**

**Comment by Infamou5** [comment]
Added PRODUCTS Migration and Seed
![image](https://user-images.githubusercontent.com/81259898/150697518-e93418e9-63a9-4e51-afcb-0fc3e23bb6d4.png)
