### ISSUE TITLE
Feature: Link to ProductPage

### ISSUE THREAD

**Issue by Impressiv3** [HackYourFuture-CPH/fp-class19#240]
### User Story
**Who:** As a developer
**What:** I want to be able to click on a product's image and be redirected to the ProductPage
**Why:** Cause this feature is missing 

### Acceptance Criteria:
When you click on a product image, you will be redirected to the ProductPage

**Comment by Infamou5** [comment]
If I add <Link to=""> it breaks the layout 
![image](https://user-images.githubusercontent.com/81259898/158239965-a32de944-6946-4999-b6d3-1013381215d8.png)

**Comment by Impressiv3** [comment]
Review and accept Divya's PR
