### ISSUE TITLE
Databases: Create Orders and OrderItems table (Migrations)

### ISSUE THREAD

**Issue by hparul** [HackYourFuture-CPH/fp-class19#51]
### **User story**
Who: As a developer of the website
What: I want to have the ORDERS and ORDERITEMS table in the Database.
Why: so that I can support the functionality of adding orders from the website.

### **Acceptance criteria**
ORDERS and ORDERITEM tables are created as per database design of the website

![order_table](https://user-images.githubusercontent.com/55456245/151676280-59a27e6a-94f0-4deb-a1f2-4decee29bdd3.jpg)

### **Implementation details**
Create orders and orderitems schema in src/server/migrations using Knex.

**Comment by Impressiv3** [comment]
Are you doing this Issue or you are just the one who created it?

**Comment by Divyajg** [comment]
Hey @Infamou5 @hparul, finished. but forgot to connect the PR to the issue.

**Comment by Divyajg** [comment]
Issue solved, PR merged.
