### ISSUE TITLE
Frontend: Product Page/Add to Cart Page

### ISSUE THREAD

**Issue by FlorentinaPetica** [HackYourFuture-CPH/fp-class19#74]
**Who**: As a developer
**What**: I want to develop Product Page/Add to Cart Page.
**Why**: So that display the product product detail, and have similar products displayed.

## Acceptance criteria
This page should look according to screenshot below:

![image](https://user-images.githubusercontent.com/81110602/152417263-8469d2b0-f858-418e-98fb-769d76c01c29.png)

## Implementation details

You will need to see in the ProductPage.container the components and elements for:
Header - [issue#4](https://github.com/HackYourFuture-CPH/fp-class19/issues/4), 
Menu - [issue#5](https://github.com/HackYourFuture-CPH/fp-class19/issues/5), 
Product Detail Component - [issue#76](https://github.com/HackYourFuture-CPH/fp-class19/issues/76)
Similar Products Carrousel - [issue#77](https://github.com/HackYourFuture-CPH/fp-class19/issues/77),
and Footer - [issue#7](https://github.com/HackYourFuture-CPH/fp-class19/issues/7)

You will also need to have an endpoint that gives you a specific product - [issue#82](https://github.com/HackYourFuture-CPH/fp-class19/issues/82)

We will also need to make sure that we have Migrations and Seeding for Products - [issue#18](https://github.com/HackYourFuture-CPH/fp-class19/issues/18)

Use the container and style file mentioned on this [issue#32](https://github.com/HackYourFuture-CPH/fp-class19/issues/32)

**Comment by JiuTak** [comment]
@Darya-s don't forget to add the link part in the Header component, please
